# Generated by Django 2.0.6 on 2019-08-13 12:02

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(help_text='Ejemplo: Dario', max_length=25)),
                ('Apellidos', models.CharField(help_text='Ejemplo: García Exposito', max_length=200)),
                ('Fecha_de_nacimiento', models.DateField(blank=True, help_text='Formato YYYY-MM-DD.  Ejemplos: 1982-06-20 o 1982-12-05    **OPTIONAL', null=True)),
                ('Tags_que_nos_vinculan', models.CharField(help_text='Cuantos más pongas mejor. Ejemplos: Tenerife, Madrid, Congreso, IAC, TLP, Indra, Kreitek, SC, Hacking, Defensa, Aikido', max_length=512)),
                ('Movil_principal', phonenumber_field.modelfields.PhoneNumberField(help_text='Ejemplo: +34611111111', max_length=128)),
                ('Movil_secundario', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Ejemplo: +34622222222    **OPTIONAL', max_length=128, null=True)),
                ('Email_principal', models.CharField(blank=True, help_text='Ejemplo: drio@mail.com', max_length=250)),
                ('Email_secundario', models.CharField(blank=True, help_text='Ejemplo: drio@yahoo.com    **OPTIONAL', max_length=250, null=True)),
                ('Direccion_de_correo_postal_principal', models.TextField(blank=True, help_text='Calle Escudero N13 B4, 28001 Madrid, España    **OPTIONAL', max_length=500, null=True)),
                ('Direccion_de_correo_postal_secundaria', models.TextField(blank=True, help_text='Calle Escudero N13 B4, 28001 Madrid, España    **OPTIONAL', max_length=500, null=True)),
                ('Usuario_en_Telegram', models.CharField(blank=True, help_text='Ejemplo: @drio    **OPTIONAL', max_length=30, null=True)),
                ('Usuario_en_Github', models.CharField(blank=True, help_text='Ejemplo: drio    **OPTIONAL', max_length=30, null=True)),
                ('Usuario_en_BitBucket', models.CharField(blank=True, help_text='Ejemplo: drio    **OPTIONAL', max_length=30, null=True)),
                ('Ultimos_lugares_donde_trabajaste', models.CharField(blank=True, help_text='Pon los tres últimos si se da el caso (incluyendo el actual) Ejemplo: Universidad, Facebook, Inem    **OPTIONAL', max_length=100, null=True)),
                ('Informacion_adicional', models.TextField(blank=True, help_text='¿Donde nos conocimos?¿Qué temas tenemos en común?    **OPTIONAL', max_length=500, null=True)),
            ],
        ),
    ]
